# Generated by Django 6.1.1 on 2026-09-20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('synopsis', models.TextField()),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('classification', models.CharField(blank=True, max_length=20)),
                ('poster_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('auditorium', models.CharField(max_length=50)),
                ('format', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.movie')),
            ],
            options={
                'ordering': ('starts_at',),
                'constraints': [models.UniqueConstraint(fields=('auditorium', 'starts_at'), name='unique_auditorium_screening_time')],
            },
        ),
    ]
